### ISSUE TITLE
I get this no matter what mode I'm using, after about the 5th or 6th download

### ISSUE THREAD

**Issue by ninjabox** [Fuyukai/pixiv-dl-py#2]
`Processed metadata for 78268977 (神無月の黎明サマと例のお子様。) with 1 pages
Downloading images concurrently...
Downloading 78271752 page 1
Downloading 78271750 page 1
Downloading 78271741 page 1
Downloading 78271736 page 1
Downloading 78271630 page 1
Downloading 78271586 page 1
Traceback (most recent call last):
  File "/usr/local/bin/pixiv-dl", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/pixiv_dl/downloader.py", line 833, in main
    return dl.download_tag(args.tag, max_items=args.limit)
  File "/usr/local/lib/python3.7/dist-packages/pixiv_dl/downloader.py", line 542, in download_tag
    list(e.map(partial(self.do_download_with_symlinks, tag_dir), to_dl))
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 435, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pixiv_dl/downloader.py", line 297, in do_download_with_symlinks
    self.download_page(items)
  File "/usr/local/lib/python3.7/dist-packages/pixiv_dl/downloader.py", line 159, in download_page
    self.retry_wrapper(p)
  File "/usr/local/lib/python3.7/dist-packages/pixiv_dl/downloader.py", line 130, in retry_wrapper
    if res is not None and "error" in res:
TypeError: argument of type 'bool' is not iterable
`

`reid@pop-os ~> for i in pixivpy tomlkit arrow termcolor; do pip3 show $i; done | grep Name\\\|Version; python3 --version
Name: PixivPy
Version: 3.5.2
Name: tomlkit
Version: 0.5.8
Name: arrow
Version: 0.15.4
Name: termcolor
Version: 1.1.0
Python 3.7.5`

**Comment by ninjabox** [comment]
hrm... I thought that would format better... I put it in backticks...

**Comment by Fuyukai** [comment]
Actually bizarre that anyone would possibly use this but I think I fixed that in a recent push
